//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBook
    {
        public eBook()
        {
            this.Chapter = new HashSet<Chapter>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string ISBN { get; set; }
    
        public virtual Bookmark Bookmark { get; set; }
        public virtual ICollection<Chapter> Chapter { get; set; }
    }
}
