//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceePubModelContainer : DbContext
    {
        public ServiceePubModelContainer()
            : base("name=ServiceePubModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Login> LoginSet { get; set; }
        public DbSet<eBook> eBookSet { get; set; }
        public DbSet<Bookmark> BookmarkSet { get; set; }
        public DbSet<Chapter> ChapterSet { get; set; }
    }
}
