//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBook
    {
        public eBook()
        {
            this.Chapter = new HashSet<Chapter>();
            this.eBookTitles = new HashSet<eBookTitles>();
            this.eBookAuthors = new HashSet<eBookAuthors>();
            this.eBookPublisher = new HashSet<eBookPublisher>();
        }
    
        public int Id { get; set; }
        public string Language { get; set; }
        public string Author { get; set; }
    
        public virtual Bookmark Bookmark { get; set; }
        public virtual ICollection<Chapter> Chapter { get; set; }
        public virtual Favorite Favorite { get; set; }
        public virtual ICollection<eBookTitles> eBookTitles { get; set; }
        public virtual ICollection<eBookAuthors> eBookAuthors { get; set; }
        public virtual ICollection<eBookPublisher> eBookPublisher { get; set; }
    }
}
