//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookmark = new HashSet<Bookmark>();
        }
    
        public int Id { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Bookmark> Bookmark { get; set; }
    }
}
